# Custos e benefícios: Becker (1968) {#sec-becker}

## Introdução

Apesar de o debate acadêmico sobre a atividade criminosa ser antigo em parte da literatura das ciências sociais^[Periódicos importantes da área de criminologia, como _Criminology_, _The British Journal of Criminology_ e _Journal of Criminal Law and Criminology_ remontam à primeira metade do século XX, com este último tendo sido fundado em 1910.], foi apenas à partir da contribuição seminal de 1968 de Gary Becker, _"Crime and Punishment: An Economic Approach"_, que a análise do crime passou a ser incorporada à lógica do modelo de escolha racional. Desde então, a área tem se expandido rapidamente e publicações nos principais periódicos das ciências econômicas têm se tornado cada vez mais recorrentes.

A ideia central que permeia o modelo proposto por Becker é a de que os indivíduos cometem crimes com base em um cálculo racional de custo-benefício em um ambiente de incerteza. Os indivíduos quando expostos à atividade criminosa decidem pela participação ou não ao levar em conta os ganhos esperados, os riscos associados à punição e o custo de oportunidade, geralmente associado aos ganhos potenciais no mercado de trabalho.

> Some persons become "criminals", therefore, not because their basic motivation differs from that of other persons, but because their benefits and costs differ.
> 
> Gary Becker, 1968, pp. 176

Dessa forma, incentivos econômicos e não-econômicos afetariam a participação no crime direta e indiretamente. Decisões de políticas públicas deveriam, portanto, levar em consideração potenciais mudanças nos incentivos para a partipação em atividades criminosas. Alguns exemplos:

- Melhores condições no mercado de trabalho local aumentariam o custo de oportunidade de decidir pela atividade criminosa ao invés do trabalho lícito. Isso aumentaria o custo esperado do crime e, ceteris paribus, levaria a uma redução da atividade ilícita.
- Ganhos esperados maiores da atividade criminosa, o que pode estar associado a um volume maior de renda disponível em um ambiente de baixa probabilidade de punição, poderiam levar a um aumento dos níveis locais de crime.
- Mudanças na percepção sobre a probabilidade de captura ou na severidade das penas levariam a alterações no custo esperado e, portanto, na decisão de cometer crime.

Para estruturar melhor esse tipo de análise de como a decisão de cometer crime é afetada por políticas públicas e mudanças no contexto social, é importante definirmos formalmente as premissas do modelo e derivar seus principais resultados.

## Estrutura do modelo

Este modelo de decisão a respeito da participação na atividade criminosa pode ser compreendido como uma aplicação direta da teoria da escolha em um ambiente de incerteza e risco. A ideia principal é a de que o criminoso potencial se depara com uma loteria com diferentes estados da natureza quando da prática do crime e uma alternativa segura, representada pela atividade lícita. Para os estados _capturado_ e _não capturado_ são atribuídos os níveis de utilidade $U_{cc}$ e $U_{cn}$, respectivamente. A utilidade auferida na atividade sem risco é dada por $U_{n}$.

[INSERIR FIGURA]

Nesse sentido, o problema de escolha com o qual o indivíduo se depara é entre praticar crime ou participar do mercado de trabalho usual. Para tal, é preciso definir algumas primitivas do modelo:

- Preferências sobre loterias são racionais, isto é, completas e transitivas.
<br>

- Preferências do indivíduo sobre loterias respeitam os axiomas de continuidade e independência.^[Para uma discussão mais profunda desses axiomas, ver @gollier2001] 
    - Alterações suficientemente pequenas nas probabilidades de ocorrência de cada estado não alteram o ordenamento de preferências entre duas loterias.
    - Se a loteria associada à atividade criminosa é preferida à atividade lícita (loteria degenerada), então uma mistura da loteria associada ao crime com uma terceira loteria também deve ser preferida à mesma mistura entre a atividade lícita e essa terceira loteria. 
<br>

- Indivíduo atribui um nível de probabilidade subjetiva $p$ à chance de ser capturado ao decidir pela atividade criminosa.

Sob a validade dessas hipóteses, as preferências do indivíduo podem ser representadas por uma função de utilidade esperada do tipo *von Neumann-Morgenstern*. A escolha, portanto, é resultado da comparação entre o nível de utilidade esperada da participação na atividade com risco (i.e., crime) com a utilidade esperada da atividade sem risco (emprego lícito). 

## Participação na atividade criminosa e estática comparativa

Suponha que a utilidade associada a cada estado seja resultado da mesma função, mas avaliada em um nível de renda (monetária e "psicológica") diferente. Seja $f$ o valor equivalente, em termos monetários, da punição quando capturado (severidade da pena, condições prisionais, estigma social pós-encarceramento, etc.). Assim, utilizando a notação original do artigo, a utilidade esperada da atividade criminosa é dada por:

$$
E(U(crime)) = pU(Y-f) + (1-p)U(Y)
$$ {#eq-EU_Becker}

em que $Y$ representa o ganho monetário de cometer o crime e $U^{'}(.)>0$. Nesse sentido, o indivíduo decide cometer crime se, e somente se,

$$ E(U(crime)) > U_{n} $$

Para ganhar mais intuição, vamos seguir @pyle1983chp2 e @chalfin2017 e redefinir alguns dos objetos acima. Assuma que a renda associada à atividade lícita seja igual a $a$ tal que $U_{n} = U(a)$. Além disso, defina $L = f - b$, em que $L$ representa o custo efetivo da punição e $b$ o benefício associado ao crime. Por fim, note que, nesse caso, o ganho monetário associado ao crime $Y$ pode ser reescrito como $a + b$. Dessa forma, o indivíduo decide pela atividade criminosa se, e somente se,

$$ E(U(crime)) = pU(a-L) + (1-p)U(a+b) > U(a) $$

Sob quais condições a inequação acima vale, i.e. o indivíduo comete crime? A resposta depende (i) da atitude do indivíduo em relação ao risco (avesso, neutro, amante) e (ii) do custo efetivo da punição ($L$), do benefício gerado pelo crime ($b$) e da probabilidade de apreensão ($p$). O gráfico abaixo representa o caso de um indivíduo avesso ao risco, com função de utilidade côncava:

[INSERIR FIGURA]

Note que o nível de utilidade associado à atividade lícita é dado por $U(a)$, localizado no ponto $C$. Já a utilidade esperada da atividade criminosa encontra-se em algum ponto do segmento de reta $AB$, tal que o ponto A representa o resultado da atividade criminosa com probabilidade de captura igual a 1 enquanto o ponto B representa a utilidade esperada para o caso em que $p=0$. Mesmo nesse caso de um indivíduo avesso ao risco, caso a renda esperada da atividade criminosa ($= p(a-L) + (1-p)(a+b)$) seja maior do que $a^\star$, o indivíduo escolhe a loteria e comete o crime. Assim, mudanças em $p$, $L$ e $b$ podem mudar a renda esperada e, portanto, a propensão do indivíduo em participar da atividade criminosa.

- Aumento da perda esperada ao ser capturado reduz a utilidade esperada de cometer crime e reduz a propensão do indivíduo participar dessa loteria.
	
    $$ \frac{\partial E(U(crime))}{\partial L} = -pU^{'}(a-L) < 0 $$
	
- Aumento da probabilidade de apreensão também reduz a utilidade esperada e a propensão a cometer crime.
	
    $$ \frac{\partial E(U(crime))}{\partial p} = U(a-L) - U(a+b) < 0 $$
	
- Por outro lado, o aumento do benefício associado a atividade criminosa aumenta a participação no crime.
	
    $$ \frac{\partial E(U(crime))}{\partial b} = (1-p)U^{'}(a+b) > 0 $$

Por fim, como exemplo adicional assuma o caso de um indivíduo neutro ao risco tal que $a^\star = a$. Nesse caso, o indivíduo estaria indiferente entre as duas atividades caso a renda esperada fosse igual a $a$. Nesse ponto, existe um nivel de benefício associado ao crime $b^\star$ dado pela relação entre $p$ e $L$ tal que:

$$ p(a-L) + (1-p)(a+b^\star) = a $$
$$ a - pL + (1-p)b^\star = a $$

$$
b^\star = L \cdot \frac{p}{(1-p)}
$$ {#eq-bstar_Becker}

Nesse caso, um aumento tanto do custo efetivo da punição quanto da probabilidade de apreensão desistimulam o crime, representado por um aumento do nível de benefício $b^\star$ necessário para manter o indivíduo indiferente entre a atividade criminosa e a atividade sem risco: 

$$\frac{\partial b^\star}{\partial L} > 0 \quad;\quad \frac{\partial b^\star}{\partial p} > 0$$

## Nível ótimo de crime e críticas ao modelo

A partir desses resultados sobre a decisão individual de escolher pela atividade criminosa, @becker1968 propõe uma oferta agregada de crimes e como essa oferta responde aos parâmetros de punição. Dada essa oferta, o autor propõe uma função de perda social como resultado do crime e argumenta que a sociedade deveria escolher a probabilidade de apreensão ($p$) e a severidade das penas/custo equivalente da punição ($f$) tendo como objetivo minimizar essas perdas. Utilizando a notação original, o problema seria dado por:

$$ \min_{p,f} \quad L = D(O) + C(p,O) + bpfO $$

\noindent em que $O$ é o número agregado de crimes, $D(.)$ é o dano líquido do crime sobre a sociedade, $C(.)$ o custo de apreensão e punição e $b$ a razão entre os custos sociais e o custo individual do crime.

Após encontrar as condições de primeira ordem do ponto de ótimo interior e adicionar algumas hipóteses a respeito do sinal das derivadas parciais, o autor sugere que existe um nível ótimo de crime positivo muito por conta do custo crescente de detecção, prevenção e punição do crime. Além disso, demonstra que a elasticidade do nível agregado de crime em relação à $f$ é menor do que a elasticidade do crime em relação à $p$, i.e., $\xi_p > \xi_f$. Nessa formulação original, isso implica que, em equilíbiro, criminosos potenciais:

- Respondem mais à alterações na probabilidade de apreensão do que alterações na severidade da pena;
- Tendem a ser amantes do risco

Tais resultados geraram bastante debate ao longo da década de 1970. Diversos autores, propondo formulações ligeiramente diferentes para a função de perda do social e de como a punição é incorporada na renda e na função utilidade, demonstraram que $\xi_p > \xi_f$ não implicava diretamente em preferência pelo risco. Além disso, o próprio resultado a respeito do tipo ótimo de punição (multas) passou a ser questionado. 

No entanto, apesar das críticas, o artigo original inaugurou uma área de pesquisa ao analisar a decisão de cometer crime sob o olhar da teoria da escolha sob incerteza. Além disso, trouxe à discussão a questão a respeito do nível ótimo de crime e dos custos e benfícios associados ao seu combate no nível agregado.