# Condições do mercado de trabalho {#sec-mercado_trabalho}

## Introdução

Enquanto aumentos na probabilidade de apreensão e severidade das punições desincentivam a atividade criminosa através de um aumento dos custos associados a essa atividade, uma melhora das condições no mercado de trabalho legal teriam o mesmo efeito de disuasão mas através do aumento dos benefícios associados à atividade não criminosa. Em essência, fontes de renda legítima representam o custo de oportunidade do crime, que embora não sejam diretamente ligadas a atividade criminosa como a probabilidade de apreensão, entram na conta de um potencial infrator que se comporta de modo racional.

Apesar da clara relação teórica, as primeiras evidências empíricas a respeito dos efeitos de salário e desemprego sobre crime não foram muito favoráveis às predições dos modelos clássicos [@freeman1999;@hjalmarsson2024]. Com a maior disponibilidade de dados administrativos e métodos modernos de identificação causal à partir de meados da década de 1990, novos artigos estudando a relação entre mercado de trabalho e crime trouxeram um conjunto de novas evidências a respeito dessa relação, agora muito mais próximas às predições teóricas iniciais. Esse literatura acabou por se dividir de acordo com a fonte de variação das condições no mercado de trabalho, em especial desemprego e salários.

## Evidências no nível agregado

### Exposição local a choques nacionais/internacionais

Entre as primeiras contribuições com aplicações de métodos mais robustos de identificação causal, podemos citar @raphael2001 e @gould2002. A preocupação central nesses artigos é identificar como choques locais nas condições do mercado de trabalho afetaram a criminalidade nos Estados Unidos entre as décadas de 1970 e 1990. @raphael2001 utilizam dados no nível dos estados americanos entre 1971 e 1997 para avaliar o efeito da taxa de desemprego sobre crime. Os autores tratam da endogeneidade do desemprego recorrendo a uma estratégia de variáveis instrumentais, construídas a partir do nível de exposição local a choques no preço do petróleo e a distribuição de contratos militares federais. A ideia é que esses choques no nível nacional/internacional deslocam a demanda por trabalho nos estados sem serem diretamente correlacionados às características locais, em especial o crime. 

@gould2002 utilizam também uma estratégia de variável instrumental, mas explorando a composição industrial do estado e em tendências nacionais específicas a cada indústria para identificar choques exógenos nas condições do mercado de trabalho local. Nesse caso, os dados são mais granulares (nível do condado americano ao invés de estado) e englobam o período de 1979 a 1997. Mesmo usando fontes de variação distintas e um nível de granularidade diferente, tanto @raphael2001 quanto @gould2002 encontram efeitos significativos que sugerem que maior desemprego causa um aumento das taxas de criminalidade. Considerados conjuntamente, os resultados sugerem que a variação nas taxas de desemprego do país foram responsáveis por algo entre $12\%$ e $40\%$ da queda em crimes contra propriedade observada nos anos 1990.

Um problema inerente a essa literatura, porém, vem do fato da análise se dar no nível local. No caso desses artigos, é difícil argumentar que as variáveis instrumentais afetam a criminalidade apenas através do desemprego, ou seja, que a restrição de exclusão é válida. Choques econômicos, como variações internacionais no preço de commodities, em geral afetam as condições do mercado de trabalho privado, mas também finanças públicas e gastos governamentais com segurança, por exemplo. 

Apesar de também utilizar dados no nível das micro-regiões brasileiras, o artigo de @dix2018 avança em várias dimensões em relação a essa literatura. Primeiro, o contexto é de um país em desenvolvimento com níveis elevados de criminalidade, onde efeitos de choques econômicos tendem a ser mais agudos. Segundo, a identificação explora um choque de liberalização comercial ocorrida no país entre 1990 e 1995, já amplamente estudado em diferentes áreas da economia (mercado de trabalho, desigualdade, provisão de bens públicos), mas aqui utilizado como experimento natural para analisar efeitos sobre crime. A @fig-DixTariffs mostra a magnitude da queda das tarifas de importação, por setor da economia, ocorrida durante o choque de abertura econômica no país.

[INSERIR FIGURA]

Ao interagir cortes tarifários setoriais com a composição ocupacional regional, os autores constroem choques exógenos de demanda local. A ideia é que regiões com parte importante da mão de obra alocada em setores mais expostos à abertura e, portanto, à concorrência internacional, sofreriam uma queda da demanda por trabalho e uma piora geral das condições do mercado de trabalho. O artigo reconhece, porém, que esse tipo de instrumento, assim como o utilizado em @raphael2001 e @gould2002, provavelmente viola a restrição de exclusão, já que as mesmas forças que afetam emprego também afetam outras variáveis ligadas ao crime. Assim, a primeira abordagem do artigo consiste em estimar uma forma reduzida, regredindo o instrumento, que mede a exposição local ao choque de abertura, direto contra a variável de interesse:

\begin{equation}
	\label{eq:dix2018_rf}
	log(CR_{r,t}) - log(CR_{r,1991}) = \theta RTC_r + \alpha_{s,t} + \epsilon_{r,t}
\end{equation}

em que $CR_{r,t}$ é a taxa de crime na micro-região $r$ e ano $t>1991$. $\alpha_{s,t}$ são efeitos fixos de estado-ano e $RTC_r$ a medida de exposição à redução das tarifas no nível da micro-região.

Os resultados principais de médio-prazo são expressos na Tabela @tab-dix2018_rf. A coluna (3), que apresenta a especificação preferida dos autores, mostra que mesmo quando há inclusão de efeitos fixos no nível do estado e as observações são ponderadas pela população de cada micro-região, o efeito de uma maior exposição à competição estrangeira ($RTC_r$ mais negativo) é de um aumento significativo^[Estatística $t = -3.838 / 1.426 = 2.68$.] das taxas de homicídio. Na colunas (4) os autores incluem as tendências de crime pré-abertura econômica, enquanto na coluna (5) essas tendências, potencialmente endógenas, são instrumentadas. Interessante notar que os efeito se mantém praticamente iguais aos da coluna (3), tanto em magnitude quanto em significância. Os autores também reportam no artigo os efeitos de longo-prazo ao comparar os dados de $1991$ com $2010$, sugerindo que, apesar da relação significante entre competição estrangeira e crime no médio-prazo, no longo-prazo o efeito do choque de abertura econômica é estatisticamente não diferente de zero. 

[INSERIR TABELA]

Para contornar o fato de que a exposição local à abertura ($RTC_r$), se utilizada como instrumento para o desemprego provavelmente violaria a restrição de exclusão, os autores desenvolvem um \textit{framework} teórico-empírico que explora a dinâmica distinta das respostas de emprego, provisão de bens públicos e desigualdade ao choque de abertura como forma de trazer insights sobre os mecanismos pelos quais a abertura afetou o crime. Esse desenho permite atribuir limites (\textit{bounds}) ao efeito do mercado de trabalho sobre crime, mostrando que entre $75\%$ e $93\%$ do impacto da liberalização sobre homicídios decorre da deterioração do emprego. Assim, além de confirmar o papel central do mercado de trabalho, o artigo também oferece um avanço metodológico ao propor uma forma de identificação parcial mais robusta do canal laboral.

Apesar de ter representado um grande avanço em relação à literatura passada, @dix2018 ainda sofre com o fato de utilizar dados no nível local e, portanto, não ser um teste propriamente dito dos mecanismos propostos nos modelos teórico iniciais. Um teste mais direto da relação entre desemprego e envolvimento na atividade criminosa se daria através do uso de dados no nível individual. Em posse desse tipo de informação granular, é possível analisar mudanças no comportamento das pessoas ao longo do tempo como resposta a choques nas condições individuais do mercado de trabalho. Embora artigos utilizando dados no nível do indivíduo existam há bastante tempo, foi apenas mais recentemente que artigos trouxeram evidências para essa questão utilizado de forma conjunta dados individuais e técnicas de identificação causal.

### Choques históricos

Uma das primeiras evidências causais a respeito dos efeitos de salários sobre o crime está também em @gould2002. Os próprios autores argumentam que, na verdade, como a participação criminal é associado a um conjunto amplo de custos fixos, o crime deve ser mais reponsivo a medidas mais permanentes das condições no mercado de trabalho, como os salários, e menos a ciclos de emprego e desemprego. Além disso, salários persistentemente baixos afetariam expectativas de longo prazo, tornando o investimento em capital humano menos atrativo e reforçando trajetórias criminais. Os resultados sugerem que salários mais baixos, em especial de homens menos educados, aumentam significativamente tanto crimes contra a propriedade quanto crimes violentos, e a magnitude do efeito dos salários é maior e mais robusta do que a do desemprego. De uma forma geral, as evidências indicam que as tendências dos salários explicam mais da metade do aumento observado em crimes violentos e crimes contra propriedade ao longo de todo o período. 

Artigos mais recentes, como @makowsky2023, analisam os efeitos de salários sobre crime através de mudanças no salário mínimo local. Nesse artigo em específico, os resultados apontam para um efeito negativo do salário mínimo sobre a probabilidade de um ex-preso cometer um novo crime. Um outro artigo interessante, que se vale de uma variação exógena no nível de salários é @bignon2017. Os autores exploram o fato de que entre 1863 e 1890 a Europa foi atingida por uma grave crise agrícola, causada pela filoxera, uma praga que ataca as videiras e que causou enormes prejuízos ao setor vinícola.^[*Filoxera: a praga que mudou o mundo do vinho*. Disponível [aqui](https://www.salton.com.br/artigo/filoxera-a-praga-que-mudou-o-mundo-do-vinho).] Em posse de dados administrativos da França para o período de 1826 a 1936, o artigo avalia os efeitos desse choque negativo no setor vinícola, com forte queda dos salários, sobre as taxas locais de crime. Os resultados sugerem um forte aumento das taxas locais de crimes contra propriedade em regiões afetadas pela praga, em linha com os mecanismos teóricos usuais. No caso dos crimes violentos, os autores reportam quedas relativas nas taxas quando comparadas as regiões afetadas com regiões não afetadas, consistente com a redução do consumo de alcool tanto pela menor disponibilidade de vinho quanto pela queda da renda individual.

## Evidências no nível individual

@britto2022 talvez seja uma das grandes contribuições recentes nessa área. Em posse dos dados do universo de contratos de trabalho de trabalhadores formais do sexo masculino no Brasil entre $2009$ e $2017\%$, os autores utilizam o nome completo dos indivíduos para buscá-los na base de processos criminais (Tribunais de Justiça - TJs) iniciados no mesmo período. Enquanto a base do mercado de trabalho permite avaliar o momento no qual um determinado trabalhador é demitido, a base de processos criminais permite avaliar se a probabilidade de envolvimento em uma atividade criminosa aumenta com a perda do emprego.

A estratégia empírica se baseia em uma abordagem de diferenças-em-diferenças em que o grupo de tratamento é definido como sendo os trabalhadores desligados em processos de demissão coletiva no período de 2012 a 2014, enquanto o grupo controle é composto por todos os trabalhadores empregados em firmas que não passaram por um evento de demissão coletiva em todo o período de análise. Cada indivíduo tratado é pareado com um indivíduo controle próximo de acordo com as seguintes características: ano de nascimento, salário, tamanho da firma, setor, estado e experiência no trabalho. As equações estática e dinâmica estimadas são dadas por

\begin{equation}
	\label{eq:britto2022_did}
	Y_{it} = \alpha + \gamma Treat_i + \beta (Treat_i \times Post_t) + \lambda Post_t + \epsilon_{it}
\end{equation}

\begin{equation}
	\label{eq:britto2022_es}
	Y_{it} = \alpha + \gamma Treat_i + \sum_{t=-P}^{T} \delta_t (Treat_i \times Time_t) + \sum_{t=-P}^{T} \lambda_t Time_t + \epsilon_{it}
\end{equation}

\noindent em que $Treat_i$ é a dummy que indica se o trabalhador $i$ faz parte do grupo de tratamento e $Post_t$ a dummy que indica o período pós-demissão. $Time_t$ é uma variável dummy que identifica o número de anos desde a demissão, de modo que $Time_1$ é igual a 1 quando $t=1$, o que representa 12 meses após a demissão. De forma análoga, $Time_{-2}$ é igual a 1 quando $t=-2$, o que representa 2 anos antes da demissão. O coeficiente de interesse no caso estático é $\beta$. No caso dinâmico, os coeficientes $\{\delta_1,...,\delta_T\}$ representam os efeitos do tratamento, $t=0$ é o período de referência e $\{\delta_{-P},...,\delta_{-1}\}$ o conjunto de coeficientes que capturam possíveis efeitos de antecipação e diferenças nas tendências pré-demissão entre os grupos tratado e controle.

Os efeitos médios sobre emprego e probabilidade de envolvimento na atividade criminosa são reportados na @tab-britto2022_did. Na média, a perda do emprego implica em um aumento da probabilidade do indivíduo ser processado criminalmente em $0.12$ pontos percentuais, o que representa um aumento de $23\%$ em relação ao \textit{baseline}. Esse efeito é concentrado em crimes economicamente motivados, como roubo e furto, mas também aparece em crimes violentos, como homicídio, com um aumento de $43\%$ e $17\%$ em relação ao \textit{baseline}, respectivamente.

[INSERIR TABELA]

Os resultados dinâmicos são representados na @fig:britto2022_es. Em todos os painéis, as tendências do grupo tratado e controle evoluem de forma semelhante antes do tratamento, sugerindo que a hipótese de tendências paralelas é válida. Os painéis A e B sugerem que, após o desligamento do trabalho via demissão coletiva, a probabilidade relativa de estar empregado e os salários caem $34\%$ e $70\%$, respectivamente. Essa diferenças entre os grupos tratado e controle diminui com o tempo, mas mesmo após 4 anos do evento, o nível de emprego e salário ainda é $13\%$ e $26\%$ menor. 

[INSERIR FIGURA]

O efeito da perda do emprego sobre a probabilidade de envolvimento criminal é representado nos painéis C-F. De maneira geral, os resultados dinâmicos sugerem que a perda do emprego aumenta consistentemente a probabilidade do indivíduo ser processado criminalmente, com um aumento da ordem de $20\%$ em relação ao \textit{baseline} e que se mantém estável mesmo 4 anos após o evento. Embora o efeito seja maior em crimes economicamente motivados, o efeito é positivo, estatisticamente significante e persistente ao longo do tempo no caso de crimes violentos, como homicídio. Analisados conjuntamente, esses resultados sugerem que a experiência de demissão inesperada pode levar o indivíduo para uma carreira criminal, com participação em atividades criminosas muito tempo após o evento da perda de emprego. Além disso, sugerem que fatores não econômicos, como stress psicológico, podem contribuir para a composição do efeito total.

Por fim, os autores se valem das regras para eligibilidade de um trabalhador ao seguro desemprego para avaliar o quanto do resultado de aumento do crime pela perda do emprego está relacionado a restrições financeiras. Ao comparar o efeito da perda de emprego em indivíduos elegíveis ao seguro desemprego \textit{vis a vis} os não-elegíveis, os autores mostram que o efeito relativo da demissão sobre o envolvimento criminal é quase que zerado nos meses em que o indivíduo recebe o seguro desemprego. No entanto, no instante em que o benefício acaba, a probabilidade de envolvimento criminal volta a subir. Os auotres concluem a partir desse conjunto de evidências que restrições de liquidez constituem o principal mecanismo pelo qual a demissão afeta a probabilidade de participação em atividades criminosas.

## Retorno relativo da atividade criminal

Os modelos básicos de economia do crime argumentam que a decisão pelo envolvimento na atividade criminosa depende da comparação entre os retornos das atividades lícita e ilícita. A literatura empírica, no entanto, concentra-se muito mais nos rendimentos legais do que nos ganhos provenientes do crime, estes últimos entendidos como os retornos econômicos da atividade criminosa. Embora a literatura tenha avançado desde então, o volume de pesquisas nessa área permanece reduzido. Isso se deve, em grande medida, às dificuldades persistentes de se obter dados confiáveis — ou mesmo qualquer dado sistemático — sobre rendimentos do crime.

@draca2019, @kirchmaier2020 e @braakmann2024 são contribuições recentes que olham para a relação entre o preço de determinados bens e os crime associados a esses bens específicos, como roubo e furto. Os trabalhos de @draca2019 e @kirchmaier2020 dialogam diretamente ao mostrar como variações nos preços de bens impactam o volume e a dinâmica dos crimes contra propriedade. O primeiro artigo analisa dados da Polícia de Londres entre 2002 e 2012 e documenta elasticidades crime-preço positivas e significativas: em média, um aumento de $10\%$ no preço de um bem eleva em $3.5\%$ a probabilidade de ele ser roubado, com efeito ainda mais intenso para metais, onde a elasticidade estimada é maior do que $1$. O segundo artigo foca no caso específico dos furtos de metais entre 2007 e 2015, período marcado por forte valorização internacional desses produtos. Em posse de dados para todo o Reino Unido, os autores mostram que os preços impulsionaram o boom de crimes, mas que a posterior queda esteve associada a operações policiais e mudanças regulatórias. Assim, em conjunto, esses artigos fornecem evidências robustas de que os criminosos respondem rapidamente a incentivos econômicos, medidos nesse caso pelo aumento do valor esperado com a atividade criminosa.

O estudo de @braakmann2024 avança além dessa literatura ao enfatizar não apenas a quantidade e o tipo de bens roubados, mas também a localização do crime em função dos retornos esperados. O foco recai sobre o mercado de ouro e a percepção de que famílias com origem no sul da Ásia e residentes no Reino Unido tendem a armazenar joias em casa. Usando dados de Londres no nível do bairro entre 2011 e 2019 e uma estratégia de diferenças-em-diferenças baseada na variação internacional do preço do ouro, os autores mostram que um aumento de $1\%$ no preço do metal gera uma elevação relativa de $0.056\%$ nos furtos em bairros com forte presença sul-asiática, o dobro da sensibilidade observada em outras localidades. O artigo reforça que os criminosos não apenas escolhem quais bens roubar com base nos preços, mas também onde cometer os delitos, deslocando esforços para áreas onde o retorno esperado é maior. Dessa forma, o artigo oferece uma contribuição central ao demonstrar que a geografia do crime é moldada pelos retornos econômicos, complementando e expandindo a agenda aberta pelos estudos anteriores.

## Conclusão

Bla bla bla

## Questões para discussão

1. X
